window.APEXWebConfig = {
  "global": {
    "template": "MILAN",
    "siteName": "Cryptosx",
    "demoMode": false,
    "gateway": "wss://api.cryptosx.io/WSGateway/",
    "theme": "dark",
    "locale": "en-US",
    "dateFormat": "M/D/YYYY",
    "timeFormat": "HH:mm:ss",
    "dateTimeFormat": "MM-DD-YYYY hh:mm",
    "phoneDefaultCountry": "US",
    "siteLogo": "site-logo.svg",
    "products": ["BTC", "ETH", "XRP", "LTC", "BCH", "USD", "EUR"],
    "instruments": ["BTCUSD", "ETHUSD", "XRPUSD", "LTCUSD", "BCHUSD", "BTCEUR", "ETHEUR", "XRPEUR", "LTCEUR", "BCHEUR", "ETHBTC", "XRPBTC", "LTCBTC", "BCHBTC"],
  },
  "SimpleExchange": {
    "active": true,
    "route": "/tradeview"
  },
  "ApiKeys": {
    "documentationLink": "https://cryptosx.io/builda/index.html#introduction"
  },
  "BalancesLayout": {
    "usePagination": true,
    "maxLines": 100
  },
  "Deposit": {
    "hideDepositBankInfo": false,
    "generateNewKey": true,
    "MinimumVerificationLevel": 1,
    "showDepositIdModal": true,
      "USD": {
      "instructions": {
        "link": {
          "url": "https://cryptosx.freshdesk.com/a/solutions/articles/44000524929-part-2-depositing-cash-to-cryptosx-international-wire-transfer-swift-",
          "text": "Still unclear? Click here for a detailed guide on deposits"
        }
      },
      "bankName": "United Coconut Planters Bank",
      "bankWireNumber": "UCPBPHMM",
      "bankAccountNumber": "20-113-001532-4"
    },
    "EUR": {
      "instructions": {
        "link": {
          "url": "https://cryptosx.freshdesk.com/a/solutions/articles/44000524929-part-2-depositing-cash-to-cryptosx-international-wire-transfer-swift-",
          "text": "Still unclear? Click here for a detailed guide on deposits"
        }
      },
      "bankName": "United Coconut Planters Bank",
      "bankWireNumber": "UCPBPHMM",
      "bankAccountNumber": "20-113-001532-4"
    }
  },
  "InstrumentSelector": {
    "instruments": ["BTCUSD", "ETHUSD", "XRPUSD", "LTCUSD", "BCHUSD", "BTCEUR", "ETHEUR", "XRPEUR", "LTCEUR", "BCHEUR", "ETHBTC", "XRPBTC", "LTCBTC", "BCHBTC"]
  },
  "Withdraw": {
    "MinimumVerificationLevel": 1
  },
  "KYC": {
    "verificationRequiredUrl": "/settings/verification",
    "UpfrontKYC": false,
    "HideUpfrontCloseButton": false,
    "KYCRedirectVerificationLevel": 0,
    "MinimumVerificationLevel": 1,
    "type": "Jumio",
    "requestIdentifier": "",
    "levels": [
    {
    "level": 0,
    "label": "Level 0",
    "button": "Increase to Level 0",
    "description":
    
    { "benefits": [ "Crypto Deposits" ], "requirements": "Register as an exchange user and verify your email." }
    ,
    "verifiedMessage": "Verified for Level 0",
    "underReviewMessage": "Application under review."
    },
    {
    "level": 1,
    "label": "Level 1",
    "button": "Increase to Level 1",
    "description":
    
    { "benefits": [ "FIAT/Crypto Deposits", "FIAT/Crypto Withdraws", "FIAT/Crypto Trading" ], "requirements": "Complete KYC Program" }
    ,
    "verifiedMessage": "Verified for Level 1",
    "underReviewMessage": "Application under review.",
    "sections": [
    
    { "label": "" }
    ]
    }
    ],
    "highlightStyle": "star"
    },
  "Pagination": {
    "maxPages": 5
  },
  "ProblemLoggingIn": {
    "showOptions": false
  },
  "RecentActivity": {
    "showTransfers": true
  },
  "RetailBuySell": {
    "roundBuyLimitPrices": false,
    "dealPrices": {
      "BTCUSD": [100, 200, 500, 1000],
      "ETHUSD": [100, 200, 500, 1000],
      "LTCUSD": [100, 200, 500, 1000],
      "BCHUSD": [100, 200, 500, 1000],
      "XRPUSD": [100, 200, 500, 1000],
      "BTCEUR": [100, 200, 500, 1000],
      "ETHEUR": [100, 200, 500, 1000],
      "LTCEUR": [100, 200, 500, 1000],
      "BCHEUR": [100, 200, 500, 1000],
      "XRPEUR": [100, 200, 500, 1000],
    }
  },
  "Settings": {
    "apiKeys": true,
    "tradeReports": true,
    "userContacts": true,
    "affiliate": true,
    "loyaltyToken": false,
    "kyc": true
  },
  "SignupForm": {
    "useEmailAsUsername": false,
    "additionalFields": [{
        "label": "Full Name",
        "name": "fullName",
        "type": "text",
        "validators": ["required"]
    },
    {
      "label": "Your Source of Funds",
      "name": "fundingSource",
      "type": "select",
      "options": {
        "salary": "Salary",
        "dividends": "Dividends",
        "inheritance": "Inheritance",
        "savings": "Savings",
        "investmentProceeds": "Investment Proceeds",
        "gift": "Gift",
        "mining": "Mining",
        "realEstate": "Real Estate",
        "loan": "Loan"
      },
      "validators": ["required"]
    }
  ],
    "privacyPolicyLink": "/?link=privacy-policy",
    "termsAndServicesLink": "/?link=terms-and-conditions"
  },
  "TradingLayout": {
    "chart": "TradingView",
    "usePagination": true,
    "maxLines": 6,
    "showDepthChart": true
  },
  "OrderHistoryData": {
    "usePagination": true
  },
  "DepthChart": {
    "depthchartzoom": 2,
    "depthChartHeight": 150,
    "depthChartTextColor": "rgb(200,200,200)",
    "depthChartTextFont": "16px",
    "depthChartTextBgColor": "rgb(26, 32, 41)",
    "depthChartXAxisTextPadding": 5,
    "depthChartYAxisTextPadding": 20,
    "depthChartBottomPadding": 0,
    "depthChartXAxisStepCnt": 10
  },
  "TradingView": {
    "timezone": "Asia/Hong_Kong",
    "locale": "en",
    "disabled_features": [
      "header_screenshot",
      "header_settings",
      "header_undo_redo",
      "header_chart_type",
      "timeframes_toolbar",
      "control_bar",
      "context_menus",
      "left_toolbar",
      "header_symbol_search",
      "header_compare",
      "use_localstorage_for_settings",
      "save_chart_properties_to_local_storage",
      "show_chart_property_page"
    ]
  },
  "Language": {
    "languageNames": {
      "af": "Afrikaans",
      "sq": "Albanian",
      "ar": "Arabic",
      "hy": "Armenian",
      "az": "Azeerbaijani",
      "eu": "Basque",
      "be": "Belarusian",
      "bn": "Bengali",
      "bs": "Bosnian",
      "bg": "Bulgarian",
      "ca": "Catalan",
      "zh": "Chinese",
      "co": "Corsican",
      "hr": "Croatian",
      "cs": "Czech",
      "da": "Danish",
      "nl": "Dutch",
      "en": "English",
      "et": "Estonian",
      "fi": "Finnish",
      "fr": "French",
      "fy": "Frisian",
      "ka": "Georgian",
      "de": "German",
      "el": "Greek",
      "hi": "Hindi",
      "hu": "Hungarian",
      "is": "Icelandic",
      "id": "Indonesian",
      "it": "Italian",
      "ja": "Japanese",
      "jw": "Javanese",
      "ko": "Korean",
      "ku": "Kurdish",
      "ky": "Kyrgyz",
      "lo": "Lao",
      "lv": "Latvian",
      "lt": "Lithuanian",
      "lb": "Luxembourgish",
      "mk": "Macedonian",
      "mg": "Malagasy",
      "ms": "Malay",
      "ml": "Malayalam",
      "mt": "Maltese",
      "mi": "Maori",
      "mn": "Mongolian",
      "my": "Myanmar",
      "ne": "Nepali",
      "no": "Norwegian",
      "ps": "Pashto",
      "fa": "Persian",
      "pl": "Polish",
      "pt": "Portuguese",
      "pa": "Punjabi",
      "ro": "Romanian",
      "ru": "Russian",
      "sm": "Samoan",
      "sr": "Serbian",
      "sk": "Slovak",
      "sl": "Slovenian",
      "so": "Somali",
      "es": "Spanish",
      "su": "Sundanese",
      "sw": "Swahili",
      "sv": "Swedish",
      "tl": "Tagalog",
      "th": "Thai",
      "tr": "Turkish",
      "uk": "Ukrainian",
      "uz": "Uzbek",
      "vi": "Vietnamese"
    }
  },
  "Footer": {
    "openInNewWindow": false,
    links: [
      [
        {
          "text": "Terms & Conditions",
          "link": "https://cryptosx.freshdesk.com/en/support/solutions/articles/44001082072-terms-and-conditions"
        },
        {
          "text": "Privacy Policy",
          "link": "https://cryptosx.freshdesk.com/en/support/solutions/articles/44001081935-privacy-policy"
        }
      ],
      [
        {
          "text": "Contact Support",
          "link": "https://cryptosx.freshdesk.com/support/home"
        },
        {
          "text": "https://cryptosx.io",
          "link": "https://cryptosx.io"
        }
      ]
    ]
  },
  "Countries": {
    "AF": "Afghanistan",
    "AX": "Åland Islands",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brazil",
    "IO": "British Indian Ocean Territory",
    "BN": "Brunei Darussalam",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo",
    "CD": "Congo, The Democratic Republic of the",
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": "Cote D'Ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Ethiopia",
    "FK": "Falkland Islands (Malvinas)",
    "FO": "Faroe Islands",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard Island and Mcdonald Islands",
    "VA": "Holy See (Vatican City State)",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran, Islamic Republic Of",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "Korea, Democratic People'S Republic of",
    "KR": "Korea, Republic of",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao People'S Democratic Republic",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libyan Arab Jamahiriya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MO": "Macao",
    "MK": "Macedonia, The Former Yugoslav Republic of",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia, Federated States of",
    "MD": "Moldova, Republic of",
    "MC": "Monaco",
    "MN": "Mongolia",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "AN": "Netherlands Antilles",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestinian Territory, Occupied",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "SH": "Saint Helena",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "PM": "Saint Pierre and Miquelon",
    "VC": "Saint Vincent and the Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "CS": "Serbia and Montenegro",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": "South Georgia and the South Sandwich Islands",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Surname",
    "SJ": "Svalbard and Jan Mayen",
    "SZ": "Swaziland",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syrian Arab Republic",
    "TW": "Taiwan, Province of China",
    "TJ": "Tajikistan",
    "TZ": "Tanzania, United Republic of",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks and Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UM": "United States Minor Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.",
    "WF": "Wallis and Futuna",
    "EH": "Western Sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW ": "Zimbabwe"
  }
}
